### ISSUE TITLE
docker-compose启动pocketbase失败

### ISSUE THREAD

**Issue by yuanshi76** [TeamWiseFlow/wiseflow#261]
以下是我的docker-compose启动文件
```
version: "3.8"
services:
  wiseflow-pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - 18090:8090
    container_name: wiseflow_pocketbase
    network_mode: bridge
    volumes:
      - /mnt/nvme0n1-4/wiseflow/pb:/pb
    restart: unless-stopped
    entrypoint: sh -c '/usr/local/bin/pocketbase superuser upsert XXXX XXXXXX --dev --dir=/pb/pb_data && /usr/local/bin/pocketbase serve --dev --http=0.0.0.0:8090 --dir=/pb/pb_data --publicDir=/pb_public --hooksDir=/pb_hooks --migrationsDir=/pb/pb_migrations'
    environment:
      - PB_SUPERUSER_EMAIL=XXXXXXX
      - PB_SUPERUSER_PASSWORD=XXXXXX
  wiseflow-core:
    image: mcr.microsoft.com/playwright/python:v1.50.0-jammy
    container_name: wiseflow_core
    volumes:
      - /mnt/nvme0n1-4/wiseflow/core:/app
      - /mnt/nvme0n1-4/wiseflow/pip_cache:/root/.cache/pip
      - /mnt/nvme0n1-4/wiseflow/core/work_dir:/work_dir
    working_dir: /app
    network_mode: bridge
    command: sh -c 'pip install -r requirements.txt && python run_task.py'
    environment:
      - PB_API_BASE=http://wiseflow-pocketbase:8090
      - PB_API_AUTH=XXXX|XXXX
      - VL_MODEL=OpenGVLab/InternVL2-26B
      - PROJECT_DIR=/work_dir
      - LLM_API_KEY=xxxxxx
      - LLM_API_BASE=http://XXXXX/v1
      - ZHIPU_API_KEY=xxxxx
      - PRIMARY_MODEL=Qwen/Qwen2.5-32B-Instruct
      - SECONDARY_MODEL=Qwen/Qwen2.5-14B-Instruct
      - LLM_CONCURRENT_NUMBER=${LLM_CONCURRENT_NUMBER:-1}
      - VERBOSE=${VERBOSE:-""}
    depends_on:
      - wiseflow-pocketbase
```
  

启动docker-compose后报错
```
wiseflow_pocketbase  | sh: --dev: not found
wiseflow_pocketbase  | sh: --dev: not found
wiseflow_pocketbase exited with code 0
wiseflow_pocketbase  | sh: --dev: not found
wiseflow_pocketbase exited with code 127
wiseflow_pocketbase exited with code 127
```
